### ISSUE TITLE
Licence file states MIT but the javascript file says GPL 2.0

### ISSUE THREAD

**Issue by Rambomst** [tableau-mkt/jquery.addressfield#38]
In the licence of it says this jquery plugin is MIT however in the javascript file it is stated as being GPL 2.0. Does this just need to be changed in the javascript file or is it actually GPL 2.0?

**Comment by iamEAP** [comment]
Hi @Rambomst.  For clarity: as of v1.0.0, this plugin is licensed MIT and the packaged / minified JavaScript files should reflect that.  Versions prior to v1.0.0 were licensed GPL2.

I see, however, that the source file mentions GPL2, which is incorrect.  I'll fix that here shortly.
