### ISSUE TITLE
Docs don't indicate structure of expected markup 

### ISSUE THREAD

**Issue by thedaniel** [tableau-mkt/jquery.addressfield#39]
I had a great deal of frustration trying to use this plugin, until I realized that I could make my `.locality` group stop disappearing if I wrapped label-input pairs in a container (e.g. `div.form-group`). The usage docs could use some explicit detail about the requirements for marking up the form.

**Comment by iamEAP** [comment]
Thanks for the report @thedaniel.  I also just received an independent report about this issue through Twitter.

I'll be working on better docs for this project soon; naturally, I'd also accept a PR.
