### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by jrock2004** [tableau-mkt/jquery.addressfield#48]
Does this plugin support localization of the fields?

**Comment by iamEAP** [comment]
Hey @jrock2004,

Localization of field labels and pick list values is supported insofar as you can bring your own JSON configuration...  In other words, you can localize the [addressfield.json](https://github.com/tableau-mkt/addressfield.json) file into your desired languages, and dynamically initialize using the JSON file corresponding to the current language UI.

This plugin only introduces one interface string (`e.g. !format`), which you can swap by overriding one very small method: https://github.com/tableau-mkt/jquery.addressfield/blob/master/src/jquery.addressfield.js#L267
