### ISSUE TITLE
Install via npm doesn't seem trustworthy

### ISSUE THREAD

**Issue by yangmillstheory** [tableau-mkt/jquery.addressfield#51]
I'm planning on having a browserified build that includes this as a dependency. There's a `package.json` in the project root, so it seems like this would work via an NPM install. Looking at `package.json`, it looks like plugin has been registered on NPM with "jquery-plugin". 

npm installing that gives me the package, but I think there are a few issues here:

1) `jquery` and `addressfield.json` aren't listened as runtime dependencies, so I don't get them with the install (unlike if I install this with bower). node will not find these dependencies at runtime, so this will likely break on a browserified build that happens to not include jquery as a separate dependency.
2) in `bower.json`, I see the main file as `dist/jquery.addressfield.js`. I don't have this however:

```shell
example $ ls -lh node_modules/jquery-plugin/dist/
total 16
-rw-r--r--  1 valvarez  TSI\Domain Users   842B Sep  7  2012 foo.js
-rw-r--r--  1 valvarez  TSI\Domain Users   435B Sep  7  2012 foo.min.js
```

3) this is more of a suggestion, but could we make the package name on NPM a bit more specific, something like "jquery.addressfield" instead of "jquery-plugin"?
4) I get development files in the distribution:

```shell
example $ ls -lh node_modules/jquery-plugin/libs/
total 8
drwxr-xr-x  3 valvarez  TSI\Domain Users   102B Sep  7  2012 jquery
-rw-r--r--  1 valvarez  TSI\Domain Users   506B Sep  7  2012 jquery-loader.js
drwxr-xr-x  4 valvarez  TSI\Domain Users   136B Jan 17 19:33 qunit
example $ ls -lh node_modules/jquery-plugin/src/
total 8
-rw-r--r--  1 valvarez  TSI\Domain Users   851B Sep  7  2012 foo.js
example $ ls -lh node_modules/jquery-plugin/test/
total 16
-rw-r--r--  1 valvarez  TSI\Domain Users   1.1K Sep  7  2012 foo.html
-rw-r--r--  1 valvarez  TSI\Domain Users   1.7K Sep  7  2012 foo_test.js
```

I also get a `foo.jquery.json` in my project root. Do I need these on my disk?

Proposed solutions:

- exclude unneeded files in `.npmignore`
- rebuild and republish to npm
- change npm package name
- enumerate jquery and addressfield.json in dependencies or peerDependencies

**Comment by yangmillstheory** [comment]
@iamEAP would you like me to work on this?

**Comment by iamEAP** [comment]
@yangmillstheory Absolutely! PRs 100% accepted.  Everything you outlined above sounds good to me.

I'm not sure this has yet been published to npm, the stuff in package.json is likely defaults from running `yo jquery-plugin` and some test dependencies.  Once that's cleaned up, I can publish there, though.
