### ISSUE TITLE
Tests Fail with qunit

### ISSUE THREAD

**Issue by lesliedoherty** [tableau-mkt/jquery.addressfield#64]
Running a test results in the following:

```
Running "qunit:all" (qunit) task
Testing test/addressfield.html?jquery=1.3.2 
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.
```
[According to this thread](https://github.com/qunitjs/qunit/issues/1048) on qunit, the [suggestion is to move away from grunt-contrib-qunit and PhantomJS](https://github.com/qunitjs/qunit/issues/1048#issuecomment-332049950) and use another testing framework instead.

>You might want to try using Karma to run the tests in a real browser (e.g. Chrome or Firefox). grunt-contrib-qunit and PhantomJS are fairly old and might not give a realistic result for end-users.

**Comment by iamEAP** [comment]
Closed in #63
