### ISSUE TITLE
Trying to implement jquery.addressfield

### ISSUE THREAD

**Issue by H2RockyRoad** [tableau-mkt/jquery.addressfield#66]
Hi, when trying to implement this library through NPM, we keep getting an error
Uncaught ReferenceError: jQuery is not defined

We added these fields to our code
`const $ = require('jquery')
require('jquery.addressfield')`

and JQuery is a dependency in our package lock

`    "jquery": {
      "version": "3.4.1",
      "resolved": "https://registry.npmjs.org/jquery/-/jquery-3.4.1.tgz",
      "integrity": "sha512-36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw=="
    },
    "jquery.addressfield": {
      "version": "1.2.3",
      "resolved": "https://registry.npmjs.org/jquery.addressfield/-/jquery.addressfield-1.2.3.tgz",
      "integrity": "sha1-7SaUISfKOUsbqx6zTJKU7bT9Y6c=",
      "requires": {
        "addressfield.json": "github:tableau-mkt/addressfield.json#1.1",
        "jquery": ">=1.3.2"
      }
    },`

We of course thought it might be our own setup, but when running the library through the RunKit link on the npm page (https://npm.runkit.com/jquery.addressfield), we experience exactly the same error at the same spot in the code.

ReferenceError: jQuery is not defined

jquery.addressfield/dist/jquery.addressfield.js — line 19

Is this library still maintained and useable?

Thank you,

Terry Fox

**Comment by jkopel** [comment]
This library is not actively maintained, but you are welcome to provide a patch. :)
